{
//=========Macro generated from canvas: ECalDigitisation/ECal Digitisation
//=========  (Wed Aug 17 10:41:19 2016) by ROOT version5.34/30
   TCanvas *ECalDigitisation = new TCanvas("ECalDigitisation", "ECal Digitisation",0,0,600,500);
   ECalDigitisation->SetHighLightColor(2);
   ECalDigitisation->Range(-1.883628,-1820.175,16.95265,16381.58);
   ECalDigitisation->SetFillColor(0);
   ECalDigitisation->SetBorderMode(0);
   ECalDigitisation->SetBorderSize(2);
   ECalDigitisation->SetFrameBorderMode(0);
   ECalDigitisation->SetFrameBorderMode(0);
   
   TH1F *CaloHitEnergyECal = new TH1F("CaloHitEnergyECal","Calorimeter Hit Energy ECal (1==nPfoTargetsTotal && 1==nPfoTargetsPhotons && Contained in ECal)",30,0,15.06903);
   CaloHitEnergyECal->SetBinContent(7,1);
   CaloHitEnergyECal->SetBinContent(8,3);
   CaloHitEnergyECal->SetBinContent(10,3);
   CaloHitEnergyECal->SetBinContent(11,1);
   CaloHitEnergyECal->SetBinContent(12,1);
   CaloHitEnergyECal->SetBinContent(13,3);
   CaloHitEnergyECal->SetBinContent(14,5);
   CaloHitEnergyECal->SetBinContent(15,7);
   CaloHitEnergyECal->SetBinContent(16,41);
   CaloHitEnergyECal->SetBinContent(17,228);
   CaloHitEnergyECal->SetBinContent(18,1778);
   CaloHitEnergyECal->SetBinContent(19,7173);
   CaloHitEnergyECal->SetBinContent(20,13868);
   CaloHitEnergyECal->SetBinContent(21,12483);
   CaloHitEnergyECal->SetBinContent(22,5566);
   CaloHitEnergyECal->SetBinContent(23,1315);
   CaloHitEnergyECal->SetBinContent(24,194);
   CaloHitEnergyECal->SetBinContent(25,12);
   CaloHitEnergyECal->SetBinContent(26,3);
   CaloHitEnergyECal->SetBinContent(27,6);
   CaloHitEnergyECal->SetBinContent(28,2);
   CaloHitEnergyECal->SetBinContent(29,1);
   CaloHitEnergyECal->SetBinContent(31,1);
   CaloHitEnergyECal->SetEntries(42695);
   
   TF1 *Gaussian_Fit_Func = new TF1("Gaussian_Fit_Func","[0]*TMath::Exp(-0.5*[2]*TMath::Power(x-[1],2))",9.292566,10.79947);
   Gaussian_Fit_Func->SetFillColor(19);
   Gaussian_Fit_Func->SetFillStyle(0);
   Gaussian_Fit_Func->SetLineColor(2);
   Gaussian_Fit_Func->SetLineWidth(2);
   Gaussian_Fit_Func->SetChisquare(1.169845e-07);
   Gaussian_Fit_Func->SetNDF(0);
   Gaussian_Fit_Func->GetXaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetXaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->SetParameter(0,14478.48);
   Gaussian_Fit_Func->SetParError(0,102.1588);
   Gaussian_Fit_Func->SetParLimits(0,0,0);
   Gaussian_Fit_Func->SetParameter(1,9.970784);
   Gaussian_Fit_Func->SetParError(1,0.01095317);
   Gaussian_Fit_Func->SetParLimits(1,0,0);
   Gaussian_Fit_Func->SetParameter(2,2.784226);
   Gaussian_Fit_Func->SetParError(2,0.09480818);
   Gaussian_Fit_Func->SetParLimits(2,0,100);
   CaloHitEnergyECal->GetListOfFunctions()->Add(Gaussian_Fit_Func);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("CaloHitEnergyECal");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 42695  ");
   text = ptstats->AddText("Mean  =  9.992");
   text = ptstats->AddText("RMS   = 0.5911");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   CaloHitEnergyECal->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(CaloHitEnergyECal);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   CaloHitEnergyECal->SetLineColor(ci);
   CaloHitEnergyECal->GetXaxis()->SetTitle("Calorimeter Hit Energy in ECal / GeV");
   CaloHitEnergyECal->GetXaxis()->SetLabelFont(42);
   CaloHitEnergyECal->GetXaxis()->SetLabelSize(0.035);
   CaloHitEnergyECal->GetXaxis()->SetTitleSize(0.035);
   CaloHitEnergyECal->GetXaxis()->SetTitleFont(42);
   CaloHitEnergyECal->GetYaxis()->SetTitle("Entries");
   CaloHitEnergyECal->GetYaxis()->SetLabelFont(42);
   CaloHitEnergyECal->GetYaxis()->SetLabelSize(0.035);
   CaloHitEnergyECal->GetYaxis()->SetTitleSize(0.035);
   CaloHitEnergyECal->GetYaxis()->SetTitleFont(42);
   CaloHitEnergyECal->GetZaxis()->SetLabelFont(42);
   CaloHitEnergyECal->GetZaxis()->SetLabelSize(0.035);
   CaloHitEnergyECal->GetZaxis()->SetTitleSize(0.035);
   CaloHitEnergyECal->GetZaxis()->SetTitleFont(42);
   CaloHitEnergyECal->Draw("");
   
   TF1 *Gaussian_Fit_Func = new TF1("Gaussian_Fit_Func","[0]*TMath::Exp(-0.5*[2]*TMath::Power(x-[1],2))",0,1);
   Gaussian_Fit_Func->SetFillColor(19);
   Gaussian_Fit_Func->SetFillStyle(0);
   Gaussian_Fit_Func->SetLineColor(2);
   Gaussian_Fit_Func->SetLineWidth(2);
   Gaussian_Fit_Func->SetChisquare(1.169845e-07);
   Gaussian_Fit_Func->SetNDF(0);
   Gaussian_Fit_Func->GetXaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetXaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->SetParameter(0,14478.48);
   Gaussian_Fit_Func->SetParError(0,102.1588);
   Gaussian_Fit_Func->SetParLimits(0,0,0);
   Gaussian_Fit_Func->SetParameter(1,9.970784);
   Gaussian_Fit_Func->SetParError(1,0.01095317);
   Gaussian_Fit_Func->SetParLimits(1,0,0);
   Gaussian_Fit_Func->SetParameter(2,2.784226);
   Gaussian_Fit_Func->SetParError(2,0.09480818);
   Gaussian_Fit_Func->SetParLimits(2,0,100);
   Gaussian_Fit_Func->Draw("same");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("Calorimeter Hit Energy ECal (1==nPfoTargetsTotal && 1==nPfoTargetsPhotons && Contained in ECal)");
   pt->Draw();
   ECalDigitisation->Modified();
   ECalDigitisation->cd();
   ECalDigitisation->SetSelected(ECalDigitisation);
}
