{
//=========Macro generated from canvas: c1/c1
//=========  (Tue Mar  7 15:53:10 2017) by ROOT version5.34/37
   TCanvas *c1 = new TCanvas("c1", "c1",10,45,700,500);
   gStyle->SetOptStat(0);
   c1->Range(0,0,1,1);
   c1->SetFillColor(0);
   c1->SetBorderMode(0);
   c1->SetBorderSize(2);
   c1->SetTickx(1);
   c1->SetTicky(1);
   c1->SetLeftMargin(0.15);
   c1->SetBottomMargin(0.15);
   c1->SetFrameLineWidth(2);
   c1->SetFrameBorderMode(0);
   
   TH1F *PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71 = new TH1F("PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71","",100,0,100);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(1,25);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(10,1);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(12,1);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(15,1);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(17,1);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(18,2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(19,6);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(20,2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(21,1);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(22,4);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(23,2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(24,4);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(25,3);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(26,5);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(27,6);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(28,2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(29,5);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(30,8);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(31,15);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(32,9);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(33,18);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(34,24);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(35,15);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(36,23);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(37,26);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(38,31);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(39,42);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(40,55);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(41,74);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(42,94);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(43,145);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(44,201);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(45,277);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(46,319);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(47,409);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(48,472);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(49,593);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(50,597);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(51,579);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(52,533);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(53,503);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(54,449);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(55,345);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(56,306);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(57,226);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(58,168);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(59,123);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(60,98);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(61,52);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(62,34);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(63,28);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(64,17);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(65,9);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(66,8);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(67,2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(68,2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(69,1);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(72,2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetBinContent(73,1);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetEntries(7004);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetStats(0);
   
   TF1 *PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV = new TF1("PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV","gaus",43.5,54.5);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetFillColor(1);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetFillStyle(0);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetLineWidth(2);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetChisquare(9.515208);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetNDF(9);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetNdivisions(505);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetLabelFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetLabelSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetTitleSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetTitleFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetLabelFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetLabelSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetTitleSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetTitleFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParameter(0,585.9691);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParError(0,11.00544);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParLimits(0,0,0);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParameter(1,50.06651);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParError(1,0.09921289);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParLimits(1,0,0);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParameter(2,4.409458);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParError(2,0.1247568);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParLimits(2,0,30.30814);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetListOfFunctions()->Add(PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->SetLineWidth(2);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetTitle("Reconstructed PFO Energy [GeV]");
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetRange(31,70);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetNdivisions(505);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetLabelFont(132);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetLabelSize(0.05);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetTitleSize(0.05);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetTitleOffset(0.95);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetXaxis()->SetTitleFont(132);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetYaxis()->SetTitle("Entries");
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetYaxis()->SetLabelFont(132);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetYaxis()->SetLabelSize(0.05);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetYaxis()->SetTitleSize(0.05);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetYaxis()->SetTitleFont(132);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetZaxis()->SetLabelFont(132);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetZaxis()->SetLabelSize(0.05);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetZaxis()->SetTitleSize(0.05);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->GetZaxis()->SetTitleFont(132);
   PFOEnergyHistogram_DetectorModel_85_ReconstructionVariant_71->Draw("");
   
   TF1 *PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV = new TF1("PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV","gaus",43.5,54.5);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetFillColor(1);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetFillStyle(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#ff0000");
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetLineColor(ci);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetLineWidth(2);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetChisquare(9.515208);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetNDF(9);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetNdivisions(505);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetLabelFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetLabelSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetTitleSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetXaxis()->SetTitleFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetLabelFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetLabelSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetTitleSize(0.05);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->GetYaxis()->SetTitleFont(132);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParameter(0,585.9691);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParError(0,11.00544);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParLimits(0,0,0);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParameter(1,50.06651);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParError(1,0.09921289);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParLimits(1,0,0);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParameter(2,4.409458);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParError(2,0.1247568);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->SetParLimits(2,0,30.30814);
   PFOEnergyHistogramGaussianFit_DetectorModel_85_ReconstructionVariant_71_Energy50GeV->Draw("same");
   
   TPaveText *pt = new TPaveText(0.01,0.945,0.08730659,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(1);
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   pt->SetTextFont(132);
   TText *text = pt->AddText("gaus");
   pt->Draw();
   c1->Modified();
   c1->cd();
   c1->SetSelected(c1);
}
