{
//=========Macro generated from canvas: BarrelDigitisation/Barrel Digitisation
//=========  (Wed Aug 17 10:47:04 2016) by ROOT version5.34/30
   TCanvas *BarrelDigitisation = new TCanvas("BarrelDigitisation", "Barrel Digitisation",0,0,600,500);
   BarrelDigitisation->SetHighLightColor(2);
   BarrelDigitisation->Range(-3.821917,-98.17501,34.39725,883.575);
   BarrelDigitisation->SetFillColor(0);
   BarrelDigitisation->SetBorderMode(0);
   BarrelDigitisation->SetBorderSize(2);
   BarrelDigitisation->SetFrameBorderMode(0);
   BarrelDigitisation->SetFrameBorderMode(0);
   
   TH1F *CaloHitEnergyHCalBarrel = new TH1F("CaloHitEnergyHCalBarrel","Calorimeter Hit Energy HCal Barrel (1==nPfoTargetsTotal && 1==nPfoTargetsNeutralHadrons && Contained in HCal)",30,0,30.57534);
   CaloHitEnergyHCalBarrel->SetBinContent(6,1);
   CaloHitEnergyHCalBarrel->SetBinContent(10,2);
   CaloHitEnergyHCalBarrel->SetBinContent(11,7);
   CaloHitEnergyHCalBarrel->SetBinContent(12,16);
   CaloHitEnergyHCalBarrel->SetBinContent(13,34);
   CaloHitEnergyHCalBarrel->SetBinContent(14,77);
   CaloHitEnergyHCalBarrel->SetBinContent(15,169);
   CaloHitEnergyHCalBarrel->SetBinContent(16,296);
   CaloHitEnergyHCalBarrel->SetBinContent(17,438);
   CaloHitEnergyHCalBarrel->SetBinContent(18,573);
   CaloHitEnergyHCalBarrel->SetBinContent(19,698);
   CaloHitEnergyHCalBarrel->SetBinContent(20,718);
   CaloHitEnergyHCalBarrel->SetBinContent(21,748);
   CaloHitEnergyHCalBarrel->SetBinContent(22,609);
   CaloHitEnergyHCalBarrel->SetBinContent(23,472);
   CaloHitEnergyHCalBarrel->SetBinContent(24,343);
   CaloHitEnergyHCalBarrel->SetBinContent(25,211);
   CaloHitEnergyHCalBarrel->SetBinContent(26,126);
   CaloHitEnergyHCalBarrel->SetBinContent(27,61);
   CaloHitEnergyHCalBarrel->SetBinContent(28,14);
   CaloHitEnergyHCalBarrel->SetBinContent(29,11);
   CaloHitEnergyHCalBarrel->SetBinContent(30,3);
   CaloHitEnergyHCalBarrel->SetBinContent(31,1);
   CaloHitEnergyHCalBarrel->SetEntries(5628);
   
   TF1 *Gaussian_Fit_Func = new TF1("Gaussian_Fit_Func","[0]*TMath::Exp(-0.5*[2]*TMath::Power(x-[1],2))",15.79726,24.96986);
   Gaussian_Fit_Func->SetFillColor(19);
   Gaussian_Fit_Func->SetFillStyle(0);
   Gaussian_Fit_Func->SetLineColor(2);
   Gaussian_Fit_Func->SetLineWidth(2);
   Gaussian_Fit_Func->SetChisquare(432.1505);
   Gaussian_Fit_Func->SetNDF(6);
   Gaussian_Fit_Func->GetXaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetXaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->SetParameter(0,504.2047);
   Gaussian_Fit_Func->SetParError(0,0.2545542);
   Gaussian_Fit_Func->SetParLimits(0,250.6923,504.2047);
   Gaussian_Fit_Func->SetParameter(1,20.22788);
   Gaussian_Fit_Func->SetParError(1,0.07696082);
   Gaussian_Fit_Func->SetParLimits(1,18.9981,28.99944);
   Gaussian_Fit_Func->SetParameter(2,0.09211278);
   Gaussian_Fit_Func->SetParError(2,0.0002157276);
   Gaussian_Fit_Func->SetParLimits(2,0.09211278,0.1506379);
   CaloHitEnergyHCalBarrel->GetListOfFunctions()->Add(Gaussian_Fit_Func);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("CaloHitEnergyHCalBarrel");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 5628   ");
   text = ptstats->AddText("Mean  =  20.08");
   text = ptstats->AddText("RMS   =  3.027");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   CaloHitEnergyHCalBarrel->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(CaloHitEnergyHCalBarrel);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#000099");
   CaloHitEnergyHCalBarrel->SetLineColor(ci);
   CaloHitEnergyHCalBarrel->GetXaxis()->SetTitle("Calorimeter Hit Energy in HCal Barrel/ GeV");
   CaloHitEnergyHCalBarrel->GetXaxis()->SetLabelFont(42);
   CaloHitEnergyHCalBarrel->GetXaxis()->SetLabelSize(0.035);
   CaloHitEnergyHCalBarrel->GetXaxis()->SetTitleSize(0.035);
   CaloHitEnergyHCalBarrel->GetXaxis()->SetTitleFont(42);
   CaloHitEnergyHCalBarrel->GetYaxis()->SetTitle("Entries");
   CaloHitEnergyHCalBarrel->GetYaxis()->SetLabelFont(42);
   CaloHitEnergyHCalBarrel->GetYaxis()->SetLabelSize(0.035);
   CaloHitEnergyHCalBarrel->GetYaxis()->SetTitleSize(0.035);
   CaloHitEnergyHCalBarrel->GetYaxis()->SetTitleFont(42);
   CaloHitEnergyHCalBarrel->GetZaxis()->SetLabelFont(42);
   CaloHitEnergyHCalBarrel->GetZaxis()->SetLabelSize(0.035);
   CaloHitEnergyHCalBarrel->GetZaxis()->SetTitleSize(0.035);
   CaloHitEnergyHCalBarrel->GetZaxis()->SetTitleFont(42);
   CaloHitEnergyHCalBarrel->Draw("");
   
   TF1 *Gaussian_Fit_Func = new TF1("Gaussian_Fit_Func","[0]*TMath::Exp(-0.5*[2]*TMath::Power(x-[1],2))",0,1);
   Gaussian_Fit_Func->SetFillColor(19);
   Gaussian_Fit_Func->SetFillStyle(0);
   Gaussian_Fit_Func->SetLineColor(2);
   Gaussian_Fit_Func->SetLineWidth(2);
   Gaussian_Fit_Func->SetChisquare(432.1505);
   Gaussian_Fit_Func->SetNDF(6);
   Gaussian_Fit_Func->GetXaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetXaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetXaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelFont(42);
   Gaussian_Fit_Func->GetYaxis()->SetLabelSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleSize(0.035);
   Gaussian_Fit_Func->GetYaxis()->SetTitleFont(42);
   Gaussian_Fit_Func->SetParameter(0,504.2047);
   Gaussian_Fit_Func->SetParError(0,0.2545542);
   Gaussian_Fit_Func->SetParLimits(0,250.6923,504.2047);
   Gaussian_Fit_Func->SetParameter(1,20.22788);
   Gaussian_Fit_Func->SetParError(1,0.07696082);
   Gaussian_Fit_Func->SetParLimits(1,18.9981,28.99944);
   Gaussian_Fit_Func->SetParameter(2,0.09211278);
   Gaussian_Fit_Func->SetParError(2,0.0002157276);
   Gaussian_Fit_Func->SetParLimits(2,0.09211278,0.1506379);
   Gaussian_Fit_Func->Draw("same");
   
   TPaveText *pt = new TPaveText(0.15,0.9339831,0.85,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("Calorimeter Hit Energy HCal Barrel (1==nPfoTargetsTotal && 1==nPfoTargetsNeutralHadrons && Contained in HCal)");
   pt->Draw();
   BarrelDigitisation->Modified();
   BarrelDigitisation->cd();
   BarrelDigitisation->SetSelected(BarrelDigitisation);
}
